# Generated by Django 3.1.1 on 2020-09-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=400)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='teachers')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('Covid_19', models.BooleanField(blank=True, default=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.ManyToManyField(to='student.Grade')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
                ('subjects', models.ManyToManyField(to='student.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='students')),
                ('name', models.CharField(max_length=100)),
                ('Covid_19', models.BooleanField(blank=True, default=False)),
                ('gaurdain_name', models.CharField(max_length=100)),
                ('Guardain_contact', models.CharField(max_length=12)),
                ('rollno', models.IntegerField(default=0)),
                ('joined', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.grade')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.school')),
            ],
        ),
    ]
